import express from "express";

// User-related controller functions
import {
    getThumbnailById,
    getUserThumbnails,
} from "../controllers/UserController.js";

// Middleware to protect user-specific routes
import protect from "../middlewares/auth.js";

// Create user router
const UserRouter = express.Router();

// Get all thumbnails generated by the logged-in user
UserRouter.get("/thumbnails", protect, getUserThumbnails);

// Get a specific thumbnail by its ID
UserRouter.get("/thumbnails/:id", protect, getThumbnailById);

export default UserRouter;